### ISSUE TITLE
Event::processBindConfigStack - bind multiple closures to eventname fails

### ISSUE THREAD

**Issue by mediafinanz** [gueff/myMVC#8]
**myMVC 3.2.x**

when binding multiple closures to an event by using `Event::processBindConfigStack`,

only the latest closure will be bonded.

_example_  
~~~
\MVC\Event::processBindConfigStack([

    'policy.index.requestMethodHasToMatchRouteMethod.after' => [

        function (\MVC\DataType\DTArrayObject $oDTArrayObject) { .. },

        function (\MVC\DataType\DTArrayObject $oDTArrayObject) { .. },
    ],
]);
~~~

**Comment by gueff** [comment]
fixed by commit [https://github.com/gueff/myMVC/commit/4797ec96ace48c2b52d7b0959402f51054569c29](https://github.com/gueff/myMVC/commit/4797ec96ace48c2b52d7b0959402f51054569c29)

**Comment by mediafinanz** [comment]
close
